language: csharp
mono: none
dotnet: 2.2.401
script:
 - dotnet build samples/TorSharp.Sandbox --framework netcoreapp2.0
 - dotnet build test/TorSharp.Tests --framework netcoreapp2.0
 - dotnet test test/TorSharp.Tests --no-build --framework netcoreapp2.0 --verbosity normal

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
